### ISSUE TITLE
Condos.sol - TypeError: Cannot read properties of null (reading '0')

### ISSUE THREAD

**Issue by i2thesecond** [PacktPublishing/Blockchain-Development-for-Finance-Projects#114]
I am having trouble compiling the Condos.sol contract.

The terminal output is below: 

```
truffle(development)> compile

Compiling your contracts...
===========================
> Compiling ./contracts/Condos.sol
TypeError: Cannot read properties of null (reading '0')
    at detectErrors (/usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:230:65)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:49:42
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:4:42)

```
I have tried copying/pasting the supplied Condos.sol code but the error remains. Please help.

**Comment by saurabhk710** [comment]
Hi @i2thesecond !

 It looks like an environment setup issue. Can you check whether you have installed truffle correctly and followed the steps as is?

**Comment by danfer** [comment]
Same issue, on Mac, unable to install truffle using sudo npm install -g, had to use yarn, nevertheless, still getting error. May be book needs updated version as seems many of them have changed at different libraries.

**Comment by JUGERNAUTUS** [comment]
Hi Danfer.

Truffle and npm are dependent softwares for the applications in the book to
run.

Reach out to the respective project teams fo any issues you might be facing.

https://phoenixnap.com/kb/install-node-js-npm-on-windows

https://trufflesuite.com/

Thanks
Ishan
